community:
  enabled: true

sonarqube:
  image:
    repository: sonarqube
    tag: 25.12.0.117093-community
    pullPolicy: IfNotPresent

postgresql:
  enabled: true
  auth:
    existingSecret: sonarqube-postgresql
    username: sonar
    database: sonarqube

monitoringPasscodeSecretName: sonarqube-monitoring
monitoringPasscodeSecretKey: monitoringPasscode

persistence:
  enabled: false

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1"
    memory: "3Gi"
